# Ejemplos de regresión logística usando Sklearn.

 Pasos necesarios:
 1. Preprocesar los datos.
 2. Realizar una reducción en dimensión.
 3. Validar los modelos.
 4. Seleccionar el modelo.
 5. Alimentar nuestro modelo a través de clasificación.
 6. Realizar predicciones.

In [28]:
# importar las librerías necesarias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [29]:
X = np.arange(10).reshape(-1,1) # Conjunto de puntos
y = np.array([0,0,0, 0, 1, 1, 1,1,1,1]) # Etiquetas binarias 


In [30]:
# Crear una instancia para la regresión logística 
modelo = LogisticRegression(solver = "liblinear", random_state = 0) 

In [31]:
modelo.fit(X, y) # Toma (X,y) y ajusta un modelo y regresa la evaluación del mismo.

LogisticRegression(random_state=0, solver='liblinear')

In [32]:
modelo.classes_ 

array([0, 1])

In [33]:
# Obtener los pesos
modelo.intercept_

array([-1.04608067])

In [34]:
modelo.coef_

array([[0.51491375]])

In [35]:
# Evaluación del modelo
M = modelo.predict_proba(X) 
M

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

In [36]:
M.shape # La primer columna de la matriz es la probabilidad de que el resultado de la variable responsiva sea 0
        # La segunda columna es la probabilidad de que el resultado sea 1

(10, 2)

In [37]:
modelo.score(X,y)

0.9